version: "3.8"
services:
  mainapp:
    build: ./mainapp
    volumes:
      - ./mainapp:/app/mainapp
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=mainapp.settings
    command: python3 manage.py runserver 0.0.0.0:8000
  mainapp-ui:
    build: ./mainapp-ui
    volumes:
      - ./mainapp-ui:/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mainapp
    command: npm start
